version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 8089:80

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 8088:80
    depends_on:
      - product-service
      
